### ISSUE TITLE
Campos de imagen

### ISSUE THREAD

**Issue by AlChara** [koxelez/cicweb#4]
campos que relacionen imagenes con algunas tablas

**Comment by koxelez** [comment]
Podrias detallar en que tablas se podria incluir campos de imagenes?

Los primeros que me vienen a la mente son:
- Eventos
- Publicaciones y Anuncios
- Personas
- Universidades

**Comment by koxelez** [comment]
Campos y subida de imagenes implementados para eventos y publicaciones. Solo fantarian personas. Universidades es superfluo.
