### ISSUE TITLE
agregar tabla asistencia persona-evento

### ISSUE THREAD

**Issue by AlChara** [koxelez/cicweb#5]
con atributos de valoración(5 estrellas) numerico , comentario puede ser nulo, y estado (aprobado, reprobado, etc) numerico

**Comment by koxelez** [comment]
a que se refiere el estado? Los comentarios van a requerir previa aprobacion por parte de moderadores o algo asi?

**Comment by koxelez** [comment]
Tabla "asiste" implementada. Reviews implementados.
